/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarnRouteImport } from './routes/earn'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiPublicOgRouteImport } from './routes/api/public/og'
import { Route as ApiPublicRobotsRouteImport } from './routes/api/public/robots'
import { Route as ApiPublicSitemapRouteImport } from './routes/api/public/sitemap'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarnRoute = EarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiPublicOgRoute = ApiPublicOgRouteImport.update({
  id: '/api/public/og',
  path: '/api/public/og',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsRoute = ApiPublicRobotsRouteImport.update({
  id: '/api/public/robots',
  path: '/api/public/robots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapRoute = ApiPublicSitemapRouteImport.update({
  id: '/api/public/sitemap',
  path: '/api/public/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/refer': typeof ReferRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/og': typeof ApiPublicOgRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/refer': typeof ReferRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/og': typeof ApiPublicOgRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/earn': typeof EarnRoute
  '/landing': typeof LandingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/redeem': typeof RedeemRoute
  '/refer': typeof ReferRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/api/public/og': typeof ApiPublicOgRoute
  '/api/public/robots': typeof ApiPublicRobotsRoute
  '/api/public/sitemap': typeof ApiPublicSitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/earn'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/redeem'
    | '/refer'
    | '/settings'
    | '/terms'
    | '/auth/callback'
    | '/api/public/og'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/earn'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/redeem'
    | '/refer'
    | '/settings'
    | '/terms'
    | '/auth/callback'
    | '/api/public/og'
    | '/api/public/robots'
    | '/api/public/sitemap'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/earn'
    | '/landing'
    | '/privacy'
    | '/profile'
    | '/redeem'
    | '/refer'
    | '/settings'
    | '/terms'
    | '/auth/callback'
    | '/api/public/og'
    | '/api/public/robots'
    | '/api/public/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EarnRoute: typeof EarnRoute
  LandingRoute: typeof LandingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RedeemRoute: typeof RedeemRoute
  ReferRoute: typeof ReferRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  ApiPublicOgRoute: typeof ApiPublicOgRoute
  ApiPublicRobotsRoute: typeof ApiPublicRobotsRoute
  ApiPublicSitemapRoute: typeof ApiPublicSitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earn': {
      id: '/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof EarnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/public/og': {
      id: '/api/public/og'
      path: '/api/public/og'
      fullPath: '/api/public/og'
      preLoaderRoute: typeof ApiPublicOgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots': {
      id: '/api/public/robots'
      path: '/api/public/robots'
      fullPath: '/api/public/robots'
      preLoaderRoute: typeof ApiPublicRobotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap': {
      id: '/api/public/sitemap'
      path: '/api/public/sitemap'
      fullPath: '/api/public/sitemap'
      preLoaderRoute: typeof ApiPublicSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EarnRoute: EarnRoute,
  LandingRoute: LandingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RedeemRoute: RedeemRoute,
  ReferRoute: ReferRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  ApiPublicOgRoute: ApiPublicOgRoute,
  ApiPublicRobotsRoute: ApiPublicRobotsRoute,
  ApiPublicSitemapRoute: ApiPublicSitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
